name: Hello 
on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest 
        steps: 
            - name: Running files 
              run: echo "hello World"